version: '3'

services:
  db:
    image: mysql:5
    environment:
      - MYSQL_USER=backend_db_user
      - MYSQL_PASSWORD=somePassword4User
      - MYSQL_DATABASE=some_db
      - MYSQL_ROOT_PASSWORD=someRootPass
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db

  rest-api:
    image: subalig/db-api:latest
    ports:
      - 80:8080
    depends_on:
      - db
# TODO create timeout before start (mysql needed some time to start)